{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
  {{- with include "microservice-chart.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- if .Values.configMap.binaryData }}
binaryData:
  {{- range $key, $value := .Values.configMap.binaryData }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
